### ISSUE TITLE
Google Maps API requires credit card for usage beginning June 11

### ISSUE THREAD

**Issue by guineawheek** [FRCDiscord/Dozer#104]
Given that we already use OpenStreetMap Nominatim to geocode the towns of teams, all we really need to do is find a library that resolves geographic coordinates to timezones.

There's a bunch of alternatives listed here:

https://stackoverflow.com/a/16086964/5927955

**Comment by tweirtx** [comment]
Reopening because I jinxed it

**Comment by tweirtx** [comment]
It's been working again. I don't think there's an issue
