### ISSUE TITLE
Dozer doesn't preserve mutes/deafen times across reboots

### ISSUE THREAD

**Issue by guineawheek** [FRCDiscord/Dozer#118]
title

**Comment by tweirtx** [comment]
I was thinking about that, my thought is to load in the moderation timers from the database when the on_ready event fires

**Comment by endreman0** [comment]
[Implementation of a similar feature](https://github.com/endreman0/Excalibot/blob/26202c0dc6a8ff3c2d033ff45fa174574d1fb279/excalibot/cogs/timer.py#L7-L15) (creating a fake context like that is dirty, but should be avoidable)

**Comment by tweirtx** [comment]
Solved by #122 once it is merged

**Comment by tweirtx** [comment]
Given that this is merged, I am closing this issue
