### ISSUE TITLE
[Information] It should be noted that the Google Maps API is no longer free to use.

### ISSUE THREAD

**Issue by royalPanic** [FRCDiscord/Dozer#150]
Similar to [this issue](https://github.com/FRCDiscord/Dozer/issues/104), as of now, the Google Maps API requires a credit card to use. This makes it fairly difficult for an average user to get the bot up and running from scratch. Is there a way to make a mode in which some functions of the bot dependent on the GMA can be disabled (a Dozer 'Lite' if you will) or at least an update to the readme to accompany these changes, so that a user may be informed before trying to set up the bot only to find that they can't.

**Comment by royalPanic** [comment]
Is there any way I can made a small update to the readme and ship it over to you guys real quick, just as a stop-gap for new users attempting to set up the bot?

**Comment by octocynth** [comment]
Sure thing, that would be welcomed. Feel free to submit a pull request and use this thread if you have any questions.

**Comment by royalPanic** [comment]
Perfect, I tried to submit a pull request earlier and it refused me with a 403, but I was using command-line git and not GitHub, so let's see if anything changes this time around.

**Comment by tweirtx** [comment]
Closing due to #151 being merged. Reopen if I'm an idiot and misreading the situation
