### ISSUE TITLE
Hide Dev-Only commands from &help

### ISSUE THREAD

**Issue by bkeeneykid** [FRCDiscord/Dozer#204]
Unless the user calling `&help` is a developer, the dev-only commands should probably be hidden from the command. This means we'll likely have to standardize the `dev_only` check throughout the cogs but I don't think it would be exceptionally hard to filter these out.

**Comment by guineawheek** [comment]
I don't know, I kinda like having people know what dev command exist.

It piques interest in the bot, yknow?

**Comment by bkeeneykid** [comment]
I think when a new user types `&help` and they get presented with 13 pages of commands, more than half of which they can't use at all, I think that is a bad new user interface. Hopefully with #187 they can use the web docs to find all of the commands, but from a normal user standpoint, I believe they should only see the commands they are able to use.
