### ISSUE TITLE
Custom config directory?

### ISSUE THREAD

**Issue by i-am-gizm0** [FRCDiscord/Dozer#258]
It would be nice to have the ability to start Dozer with a custom-defined config directory on the command line

**Comment by tweirtx** [comment]
Hi there, I'm having a hard time seeing a use case for this. Do you have one in mind?

**Comment by i-am-gizm0** [comment]
It's not strictly necessary, but I'm thinking of dockerizing Dozer and while mounting the whole Dozer directory *would* work, it's not ideal and it'd be nice to just be able to mount a folder with the `config.json`

**Comment by guineawheek** [comment]
Dozer pulls its `config.json` from its current running directory, so in theory you could start the bot from a different cwd. Alternatively,
you could symlink `config.json` to where it's mounted, to no discernable difference.

Keep in mind that you also need a Postgres instance to boot Dozer.

**Comment by tweirtx** [comment]
I see your point and your use case, however I have to agree with Guinea that it'd simply be easier to do it that way.
