### ISSUE TITLE
Discord.py is back

### ISSUE THREAD

**Issue by BCurbs** [FRCDiscord/Dozer#362]
With the return of discord.py, should we consider moving back to it from pycord?

**Comment by devyntk** [comment]
That's absolutely the plan. We can start making changed for the release for it but I don't feel comfortable pushing out the new discord py until it's stable.

**Comment by BCurbs** [comment]
yep that makes complete sense

**Comment by tweirtx** [comment]
The 2.0 merge is complete, closing this
