### ISSUE TITLE
Running &help in PM throws error

### ISSUE THREAD

**Issue by elevenchars** [FRCDiscord/Dozer#44]
When trying to use the emoji interface from `&help` in a dm, Dozer throws an error because (i am assuming, i haven't checked) that it can't remove the user's reaction.
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/11055681/32411682-d6bd1736-c1af-11e7-9b69-7caaa5d20cd8.png">

**Comment by atf1999** [comment]
Chances are we need to restrict dozer's commands to strictly be in server channels (Ian would probably know of a better way though)

**Comment by endreman0** [comment]
Right now the Reactor class doesn't check whether it has permission to remove others' reactions (which comes from the Manage Messages permission) before trying. It's expected that the caller figures out if they have permission first, then tells the Reactor whether or not to remove reactions based on that. Either ensuring that check happens everywhere Reactor is used, or making the check part of Reactor itself, is fine by me.

**Comment by guineawheek** [comment]
Perhaps the correct course of action in this situation (especially if Dozer lacks manage messages perms in a server) would be to DM all the help pages to the caller

**Comment by endreman0** [comment]
Help will still work without the permission; the only thing it's used for is removing reactions when they're consumed. Without the permission, the only change is the user would have to tap the reaction once to add their reaction and then once again to remove it manually.

**Comment by tweirtx** [comment]
The fix for this could be applied to the bot in general. Basically it would be to check if the bot has the permission it needs to remove the reaction, if it does act normally, if it doesn't then don't try to remove reactions and potentially say that you just need to click twice for the reaction to register.

**Comment by tweirtx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix the no-perms error on &help (see GitHub for my take on the fix)](https://trello.com/c/axn62ypN/50-fix-the-no-perms-error-on-help-see-github-for-my-take-on-the-fix)
