### ISSUE TITLE
[Meta] Making it easier to PR changes

### ISSUE THREAD

**Issue by guineawheek** [FRCDiscord/Dozer#451]
The FTC server:
* seeks to not diverge with upstream Dozer
* while still doing bot dev for immediately needed features

However due to everyone here having a life where Dozer dev is a D+ tier priority at best it's been hard to get enough reviews to get things merged.

As discussed in other channels the proposed solutions are as follows

* Lower the bar for PR mergers to 1 approving write-access reviewer
* Give @abidingabi (lead FTC fork maintainer) write access to this repo as a reviewer

**Comment by tweirtx** [comment]
Done.
