### ISSUE TITLE
BUG: CD Newsfeed is not pushing after 10/26/23

### ISSUE THREAD

**Issue by witherslayer67** [FRCDiscord/Dozer#452]
We have dozer set up in our team server, and after 10/26, it has not pushed anything CD wise since then.

**Comment by tweirtx** [comment]
| ERROR    | dozer.cogs.news:startup:141 - Parsing error in source cd: mismatched tag: line 1, column 368 

I think somehow CD's RSS feed got corrupted...not sure how that happened, nor is that something I can really fix

**Comment by tweirtx** [comment]
Update: CloudFlare strikes again. Opening a forum thread with CD to see if this can be fixed.
