### ISSUE TITLE
Handle teams which don't exist in &tba

### ISSUE THREAD

**Issue by bkeeneykid** [FRCDiscord/Dozer#49]

**Comment by 770352** [comment]
A patch is currently in the PRs.

**Comment by tweirtx** [comment]
Currently linked to PR #54

**Comment by tweirtx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix TBA non-existent team handling](https://trello.com/c/1NdZrjnM/58-fix-tba-non-existent-team-handling)

**Comment by 770352** [comment]
@tweirtx Can you please close this?
