### ISSUE TITLE
Selfdeafen does not undeafen

### ISSUE THREAD

**Issue by endreman0** [FRCDiscord/Dozer#62]
Selfdeafen command, for any time (valid or invalid), with any reason or no reason, produces error `TypeError: punishmenttimer() missing 1 required positional argument: 'reason'` after deafening and does not undeafen

**Comment by tweirtx** [comment]
Fixed, pushing soon

**Comment by tweirtx** [comment]
Fixed in PR #63

**Comment by tweirtx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Self deafens don't undeafen](https://trello.com/c/eBbaZreP/61-self-deafens-dont-undeafen)
